#############################################################################
# Makefile for building: tvp
# Generated by qmake (2.01a) (Qt 4.7.4) on: út 9 27 14:48:08 2011
# Project:  tvp.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile tvp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include -I. -Imodel -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = channelsDialog.cpp \
		channelsModel.cpp \
		keys.cpp \
		main.cpp \
		progView.cpp \
		tipDialog.cpp \
		tvp.cpp \
		model/Actor.cpp \
		model/Adapter.cpp \
		model/Aspect.cpp \
		model/Audio.cpp \
		model/Category.cpp \
		model/Channel.cpp \
		model/Colour.cpp \
		model/Commentator.cpp \
		model/Composer.cpp \
		model/Country.cpp \
		model/Credits.cpp \
		model/Date.cpp \
		model/Desc.cpp \
		model/Director.cpp \
		model/DisplayName.cpp \
		model/Editor.cpp \
		model/EpisodeNum.cpp \
		model/Guest.cpp \
		model/Icon.cpp \
		model/Language.cpp \
		model/LastChance.cpp \
		model/Length.cpp \
		model/New.cpp \
		model/OrigLanguage.cpp \
		model/Premiere.cpp \
		model/Present.cpp \
		model/Presenter.cpp \
		model/PreviouslyShown.cpp \
		model/Producer.cpp \
		model/Programme.cpp \
		model/Quality.cpp \
		model/Rating.cpp \
		model/Review.cpp \
		model/StarRating.cpp \
		model/Stereo.cpp \
		model/SubTitle.cpp \
		model/Subtitles.cpp \
		model/Title.cpp \
		model/Tv.cpp \
		model/Url.cpp \
		model/Value.cpp \
		model/Video.cpp \
		model/Writer.cpp moc_tvp.cpp
OBJECTS       = channelsDialog.o \
		channelsModel.o \
		keys.o \
		main.o \
		progView.o \
		tipDialog.o \
		tvp.o \
		Actor.o \
		Adapter.o \
		Aspect.o \
		Audio.o \
		Category.o \
		Channel.o \
		Colour.o \
		Commentator.o \
		Composer.o \
		Country.o \
		Credits.o \
		Date.o \
		Desc.o \
		Director.o \
		DisplayName.o \
		Editor.o \
		EpisodeNum.o \
		Guest.o \
		Icon.o \
		Language.o \
		LastChance.o \
		Length.o \
		New.o \
		OrigLanguage.o \
		Premiere.o \
		Present.o \
		Presenter.o \
		PreviouslyShown.o \
		Producer.o \
		Programme.o \
		Quality.o \
		Rating.o \
		Review.o \
		StarRating.o \
		Stereo.o \
		SubTitle.o \
		Subtitles.o \
		Title.o \
		Tv.o \
		Url.o \
		Value.o \
		Video.o \
		Writer.o \
		moc_tvp.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		tvp.pro
QMAKE_TARGET  = tvp
DESTDIR       = 
TARGET        = tvp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tvp.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile tvp.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile tvp.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/tvp1.0.0 || $(MKDIR) .tmp/tvp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tvp1.0.0/ && $(COPY_FILE) --parents channelsDialog.h channelsModel.h keys.h progView.h tipDialog.h tvp.h model/Actor.h model/Adapter.h model/Aspect.h model/Audio.h model/Category.h model/Channel.h model/Colour.h model/Commentator.h model/Composer.h model/Country.h model/Credits.h model/Date.h model/Desc.h model/Director.h model/DisplayName.h model/Editor.h model/EpisodeNum.h model/Guest.h model/Icon.h model/Language.h model/LastChance.h model/Length.h model/New.h model/OrigLanguage.h model/Premiere.h model/Present.h model/Presenter.h model/PreviouslyShown.h model/Producer.h model/Programme.h model/Quality.h model/Rating.h model/Review.h model/StarRating.h model/Stereo.h model/SubTitle.h model/Subtitles.h model/Title.h model/Tv.h model/Url.h model/Value.h model/Video.h model/Writer.h .tmp/tvp1.0.0/ && $(COPY_FILE) --parents channelsDialog.cpp channelsModel.cpp keys.cpp main.cpp progView.cpp tipDialog.cpp tvp.cpp model/Actor.cpp model/Adapter.cpp model/Aspect.cpp model/Audio.cpp model/Category.cpp model/Channel.cpp model/Colour.cpp model/Commentator.cpp model/Composer.cpp model/Country.cpp model/Credits.cpp model/Date.cpp model/Desc.cpp model/Director.cpp model/DisplayName.cpp model/Editor.cpp model/EpisodeNum.cpp model/Guest.cpp model/Icon.cpp model/Language.cpp model/LastChance.cpp model/Length.cpp model/New.cpp model/OrigLanguage.cpp model/Premiere.cpp model/Present.cpp model/Presenter.cpp model/PreviouslyShown.cpp model/Producer.cpp model/Programme.cpp model/Quality.cpp model/Rating.cpp model/Review.cpp model/StarRating.cpp model/Stereo.cpp model/SubTitle.cpp model/Subtitles.cpp model/Title.cpp model/Tv.cpp model/Url.cpp model/Value.cpp model/Video.cpp model/Writer.cpp .tmp/tvp1.0.0/ && (cd `dirname .tmp/tvp1.0.0` && $(TAR) tvp1.0.0.tar tvp1.0.0 && $(COMPRESS) tvp1.0.0.tar) && $(MOVE) `dirname .tmp/tvp1.0.0`/tvp1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tvp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_tvp.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_tvp.cpp
moc_tvp.cpp: model/Tv.h \
		model/Programme.h \
		model/Icon.h \
		model/Category.h \
		model/SubTitle.h \
		model/LastChance.h \
		model/Audio.h \
		model/Present.h \
		model/Stereo.h \
		model/Subtitles.h \
		model/Language.h \
		model/Date.h \
		model/PreviouslyShown.h \
		model/Country.h \
		model/OrigLanguage.h \
		model/StarRating.h \
		model/Value.h \
		model/Credits.h \
		model/Composer.h \
		model/Commentator.h \
		model/Writer.h \
		model/Director.h \
		model/Producer.h \
		model/Presenter.h \
		model/Actor.h \
		model/Adapter.h \
		model/Guest.h \
		model/Editor.h \
		model/Title.h \
		model/Video.h \
		model/Colour.h \
		model/Quality.h \
		model/Aspect.h \
		model/New.h \
		model/Rating.h \
		model/EpisodeNum.h \
		model/Length.h \
		model/Url.h \
		model/Review.h \
		model/Premiere.h \
		model/Desc.h \
		model/Channel.h \
		model/DisplayName.h \
		progView.h \
		tvp.h
	/usr/bin/moc $(DEFINES) $(INCPATH) tvp.h -o moc_tvp.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

channelsDialog.o: channelsDialog.cpp channelsDialog.h \
		channelsModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channelsDialog.o channelsDialog.cpp

channelsModel.o: channelsModel.cpp channelsModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channelsModel.o channelsModel.cpp

keys.o: keys.cpp keys.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keys.o keys.cpp

main.o: main.cpp tvp.h \
		model/Tv.h \
		model/Programme.h \
		model/Icon.h \
		model/Category.h \
		model/SubTitle.h \
		model/LastChance.h \
		model/Audio.h \
		model/Present.h \
		model/Stereo.h \
		model/Subtitles.h \
		model/Language.h \
		model/Date.h \
		model/PreviouslyShown.h \
		model/Country.h \
		model/OrigLanguage.h \
		model/StarRating.h \
		model/Value.h \
		model/Credits.h \
		model/Composer.h \
		model/Commentator.h \
		model/Writer.h \
		model/Director.h \
		model/Producer.h \
		model/Presenter.h \
		model/Actor.h \
		model/Adapter.h \
		model/Guest.h \
		model/Editor.h \
		model/Title.h \
		model/Video.h \
		model/Colour.h \
		model/Quality.h \
		model/Aspect.h \
		model/New.h \
		model/Rating.h \
		model/EpisodeNum.h \
		model/Length.h \
		model/Url.h \
		model/Review.h \
		model/Premiere.h \
		model/Desc.h \
		model/Channel.h \
		model/DisplayName.h \
		progView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

progView.o: progView.cpp progView.h \
		model/Programme.h \
		model/Icon.h \
		model/Category.h \
		model/SubTitle.h \
		model/LastChance.h \
		model/Audio.h \
		model/Present.h \
		model/Stereo.h \
		model/Subtitles.h \
		model/Language.h \
		model/Date.h \
		model/PreviouslyShown.h \
		model/Country.h \
		model/OrigLanguage.h \
		model/StarRating.h \
		model/Value.h \
		model/Credits.h \
		model/Composer.h \
		model/Commentator.h \
		model/Writer.h \
		model/Director.h \
		model/Producer.h \
		model/Presenter.h \
		model/Actor.h \
		model/Adapter.h \
		model/Guest.h \
		model/Editor.h \
		model/Title.h \
		model/Video.h \
		model/Colour.h \
		model/Quality.h \
		model/Aspect.h \
		model/New.h \
		model/Rating.h \
		model/EpisodeNum.h \
		model/Length.h \
		model/Url.h \
		model/Review.h \
		model/Premiere.h \
		model/Desc.h \
		keys.h \
		tipDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o progView.o progView.cpp

tipDialog.o: tipDialog.cpp tipDialog.h \
		model/Programme.h \
		model/Icon.h \
		model/Category.h \
		model/SubTitle.h \
		model/LastChance.h \
		model/Audio.h \
		model/Present.h \
		model/Stereo.h \
		model/Subtitles.h \
		model/Language.h \
		model/Date.h \
		model/PreviouslyShown.h \
		model/Country.h \
		model/OrigLanguage.h \
		model/StarRating.h \
		model/Value.h \
		model/Credits.h \
		model/Composer.h \
		model/Commentator.h \
		model/Writer.h \
		model/Director.h \
		model/Producer.h \
		model/Presenter.h \
		model/Actor.h \
		model/Adapter.h \
		model/Guest.h \
		model/Editor.h \
		model/Title.h \
		model/Video.h \
		model/Colour.h \
		model/Quality.h \
		model/Aspect.h \
		model/New.h \
		model/Rating.h \
		model/EpisodeNum.h \
		model/Length.h \
		model/Url.h \
		model/Review.h \
		model/Premiere.h \
		model/Desc.h \
		progView.h \
		keys.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tipDialog.o tipDialog.cpp

tvp.o: tvp.cpp tvp.h \
		model/Tv.h \
		model/Programme.h \
		model/Icon.h \
		model/Category.h \
		model/SubTitle.h \
		model/LastChance.h \
		model/Audio.h \
		model/Present.h \
		model/Stereo.h \
		model/Subtitles.h \
		model/Language.h \
		model/Date.h \
		model/PreviouslyShown.h \
		model/Country.h \
		model/OrigLanguage.h \
		model/StarRating.h \
		model/Value.h \
		model/Credits.h \
		model/Composer.h \
		model/Commentator.h \
		model/Writer.h \
		model/Director.h \
		model/Producer.h \
		model/Presenter.h \
		model/Actor.h \
		model/Adapter.h \
		model/Guest.h \
		model/Editor.h \
		model/Title.h \
		model/Video.h \
		model/Colour.h \
		model/Quality.h \
		model/Aspect.h \
		model/New.h \
		model/Rating.h \
		model/EpisodeNum.h \
		model/Length.h \
		model/Url.h \
		model/Review.h \
		model/Premiere.h \
		model/Desc.h \
		model/Channel.h \
		model/DisplayName.h \
		progView.h \
		keys.h \
		channelsDialog.h \
		channelsModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tvp.o tvp.cpp

Actor.o: model/Actor.cpp model/Actor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Actor.o model/Actor.cpp

Adapter.o: model/Adapter.cpp model/Adapter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Adapter.o model/Adapter.cpp

Aspect.o: model/Aspect.cpp model/Aspect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Aspect.o model/Aspect.cpp

Audio.o: model/Audio.cpp model/Audio.h \
		model/Present.h \
		model/Stereo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Audio.o model/Audio.cpp

Category.o: model/Category.cpp model/Category.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Category.o model/Category.cpp

Channel.o: model/Channel.cpp model/Channel.h \
		model/DisplayName.h \
		model/Icon.h \
		model/Url.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Channel.o model/Channel.cpp

Colour.o: model/Colour.cpp model/Colour.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Colour.o model/Colour.cpp

Commentator.o: model/Commentator.cpp model/Commentator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Commentator.o model/Commentator.cpp

Composer.o: model/Composer.cpp model/Composer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Composer.o model/Composer.cpp

Country.o: model/Country.cpp model/Country.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Country.o model/Country.cpp

Credits.o: model/Credits.cpp model/Credits.h \
		model/Composer.h \
		model/Commentator.h \
		model/Writer.h \
		model/Director.h \
		model/Producer.h \
		model/Presenter.h \
		model/Actor.h \
		model/Adapter.h \
		model/Guest.h \
		model/Editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Credits.o model/Credits.cpp

Date.o: model/Date.cpp model/Date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Date.o model/Date.cpp

Desc.o: model/Desc.cpp model/Desc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Desc.o model/Desc.cpp

Director.o: model/Director.cpp model/Director.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Director.o model/Director.cpp

DisplayName.o: model/DisplayName.cpp model/DisplayName.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DisplayName.o model/DisplayName.cpp

Editor.o: model/Editor.cpp model/Editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Editor.o model/Editor.cpp

EpisodeNum.o: model/EpisodeNum.cpp model/EpisodeNum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EpisodeNum.o model/EpisodeNum.cpp

Guest.o: model/Guest.cpp model/Guest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Guest.o model/Guest.cpp

Icon.o: model/Icon.cpp model/Icon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Icon.o model/Icon.cpp

Language.o: model/Language.cpp model/Language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Language.o model/Language.cpp

LastChance.o: model/LastChance.cpp model/LastChance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LastChance.o model/LastChance.cpp

Length.o: model/Length.cpp model/Length.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Length.o model/Length.cpp

New.o: model/New.cpp model/New.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o New.o model/New.cpp

OrigLanguage.o: model/OrigLanguage.cpp model/OrigLanguage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OrigLanguage.o model/OrigLanguage.cpp

Premiere.o: model/Premiere.cpp model/Premiere.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Premiere.o model/Premiere.cpp

Present.o: model/Present.cpp model/Present.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Present.o model/Present.cpp

Presenter.o: model/Presenter.cpp model/Presenter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Presenter.o model/Presenter.cpp

PreviouslyShown.o: model/PreviouslyShown.cpp model/PreviouslyShown.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PreviouslyShown.o model/PreviouslyShown.cpp

Producer.o: model/Producer.cpp model/Producer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Producer.o model/Producer.cpp

Programme.o: model/Programme.cpp model/Programme.h \
		model/Icon.h \
		model/Category.h \
		model/SubTitle.h \
		model/LastChance.h \
		model/Audio.h \
		model/Present.h \
		model/Stereo.h \
		model/Subtitles.h \
		model/Language.h \
		model/Date.h \
		model/PreviouslyShown.h \
		model/Country.h \
		model/OrigLanguage.h \
		model/StarRating.h \
		model/Value.h \
		model/Credits.h \
		model/Composer.h \
		model/Commentator.h \
		model/Writer.h \
		model/Director.h \
		model/Producer.h \
		model/Presenter.h \
		model/Actor.h \
		model/Adapter.h \
		model/Guest.h \
		model/Editor.h \
		model/Title.h \
		model/Video.h \
		model/Colour.h \
		model/Quality.h \
		model/Aspect.h \
		model/New.h \
		model/Rating.h \
		model/EpisodeNum.h \
		model/Length.h \
		model/Url.h \
		model/Review.h \
		model/Premiere.h \
		model/Desc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Programme.o model/Programme.cpp

Quality.o: model/Quality.cpp model/Quality.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Quality.o model/Quality.cpp

Rating.o: model/Rating.cpp model/Rating.h \
		model/Icon.h \
		model/Value.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rating.o model/Rating.cpp

Review.o: model/Review.cpp model/Review.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Review.o model/Review.cpp

StarRating.o: model/StarRating.cpp model/StarRating.h \
		model/Icon.h \
		model/Value.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StarRating.o model/StarRating.cpp

Stereo.o: model/Stereo.cpp model/Stereo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stereo.o model/Stereo.cpp

SubTitle.o: model/SubTitle.cpp model/SubTitle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SubTitle.o model/SubTitle.cpp

Subtitles.o: model/Subtitles.cpp model/Subtitles.h \
		model/Language.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Subtitles.o model/Subtitles.cpp

Title.o: model/Title.cpp model/Title.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Title.o model/Title.cpp

Tv.o: model/Tv.cpp model/Tv.h \
		model/Programme.h \
		model/Icon.h \
		model/Category.h \
		model/SubTitle.h \
		model/LastChance.h \
		model/Audio.h \
		model/Present.h \
		model/Stereo.h \
		model/Subtitles.h \
		model/Language.h \
		model/Date.h \
		model/PreviouslyShown.h \
		model/Country.h \
		model/OrigLanguage.h \
		model/StarRating.h \
		model/Value.h \
		model/Credits.h \
		model/Composer.h \
		model/Commentator.h \
		model/Writer.h \
		model/Director.h \
		model/Producer.h \
		model/Presenter.h \
		model/Actor.h \
		model/Adapter.h \
		model/Guest.h \
		model/Editor.h \
		model/Title.h \
		model/Video.h \
		model/Colour.h \
		model/Quality.h \
		model/Aspect.h \
		model/New.h \
		model/Rating.h \
		model/EpisodeNum.h \
		model/Length.h \
		model/Url.h \
		model/Review.h \
		model/Premiere.h \
		model/Desc.h \
		model/Channel.h \
		model/DisplayName.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tv.o model/Tv.cpp

Url.o: model/Url.cpp model/Url.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Url.o model/Url.cpp

Value.o: model/Value.cpp model/Value.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Value.o model/Value.cpp

Video.o: model/Video.cpp model/Video.h \
		model/Present.h \
		model/Colour.h \
		model/Quality.h \
		model/Aspect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Video.o model/Video.cpp

Writer.o: model/Writer.cpp model/Writer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Writer.o model/Writer.cpp

moc_tvp.o: moc_tvp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tvp.o moc_tvp.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

